begin;

alter table public.workbooks
  add column if not exists file_kind text not null default 'spreadsheet';

alter table public.workbooks
  add column if not exists pipeline_stage text not null default 'calculation';

update public.workbooks as workbook
set file_kind = 'elementar',
    pipeline_stage = 'publication'
where exists (
  select 1
  from public.elementar_configs as config
  where config.workbook_id = workbook.id
);

alter table public.workbooks
  drop constraint if exists workbooks_file_pipeline_check;

alter table public.workbooks
  add constraint workbooks_file_pipeline_check check (
    (file_kind = 'base' and pipeline_stage in ('source', 'treated'))
    or (file_kind = 'spreadsheet' and pipeline_stage = 'calculation')
    or (file_kind = 'elementar' and pipeline_stage = 'publication')
  );

create index if not exists workbooks_project_pipeline_idx
  on public.workbooks (project_id, pipeline_stage, updated_at desc);

create table if not exists public.base_columns (
  id bigint generated by default as identity primary key,
  workbook_id bigint not null references public.workbooks(id) on delete cascade,
  column_key text not null,
  name text not null,
  data_type text not null default 'text'
    check (data_type in ('text', 'number', 'boolean', 'date', 'datetime', 'json')),
  position integer not null check (position >= 0),
  required boolean not null default false,
  default_value jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint base_columns_workbook_key_unique unique (workbook_id, column_key),
  constraint base_columns_workbook_position_unique unique (workbook_id, position)
);

create index if not exists base_columns_workbook_order_idx
  on public.base_columns (workbook_id, position);

create table if not exists public.base_rows (
  id bigint generated by default as identity primary key,
  workbook_id bigint not null references public.workbooks(id) on delete cascade,
  row_order bigint not null check (row_order >= 0),
  values jsonb not null default '{}'::jsonb
    check (jsonb_typeof(values) = 'object'),
  revision bigint not null default 1 check (revision > 0),
  created_by_email text,
  updated_by_email text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint base_rows_workbook_order_unique unique (workbook_id, row_order)
);

create index if not exists base_rows_workbook_window_idx
  on public.base_rows (workbook_id, row_order, id);

create table if not exists public.file_dependencies (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  source_workbook_id bigint not null references public.workbooks(id) on delete cascade,
  target_workbook_id bigint not null references public.workbooks(id) on delete cascade,
  created_by_email text,
  created_at timestamptz not null default now(),
  constraint file_dependencies_distinct_check check (source_workbook_id <> target_workbook_id),
  constraint file_dependencies_unique unique (source_workbook_id, target_workbook_id)
);

create index if not exists file_dependencies_project_idx
  on public.file_dependencies (project_id, source_workbook_id, target_workbook_id);

create or replace function public.validate_file_dependency_stage()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  source_row public.workbooks%rowtype;
  target_row public.workbooks%rowtype;
begin
  select * into source_row from public.workbooks where id = new.source_workbook_id;
  select * into target_row from public.workbooks where id = new.target_workbook_id;

  if source_row.id is null or target_row.id is null then
    raise exception 'Arquivo de origem ou destino não encontrado.';
  end if;

  if source_row.project_id is distinct from target_row.project_id
     or new.project_id is distinct from source_row.project_id then
    raise exception 'A dependência deve permanecer dentro do mesmo projeto.';
  end if;

  if not (
    (source_row.pipeline_stage = 'source' and target_row.pipeline_stage = 'calculation')
    or (source_row.pipeline_stage = 'calculation' and target_row.pipeline_stage = 'treated')
    or (source_row.pipeline_stage = 'treated' and target_row.pipeline_stage = 'publication')
  ) then
    raise exception 'Dependência inválida. Use Base -> Planilhas -> Base 2 -> Elementar.';
  end if;

  return new;
end;
$$;

drop trigger if exists file_dependencies_validate_stage on public.file_dependencies;
create trigger file_dependencies_validate_stage
before insert or update on public.file_dependencies
for each row execute function public.validate_file_dependency_stage();

create or replace function public.validate_base_storage_workbook()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  kind text;
begin
  select file_kind into kind from public.workbooks where id = new.workbook_id;
  if kind is distinct from 'base' then
    raise exception 'Registros relacionais só podem pertencer a arquivos Base.';
  end if;
  return new;
end;
$$;

drop trigger if exists base_columns_validate_workbook on public.base_columns;
create trigger base_columns_validate_workbook
before insert or update of workbook_id on public.base_columns
for each row execute function public.validate_base_storage_workbook();

drop trigger if exists base_rows_validate_workbook on public.base_rows;
create trigger base_rows_validate_workbook
before insert or update of workbook_id on public.base_rows
for each row execute function public.validate_base_storage_workbook();

create or replace function public.touch_base_workbooks_from_new_rows()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  update public.workbooks as workbook
     set revision = workbook.revision + 1,
         updated_at = now()
   where workbook.id in (select distinct workbook_id from new_rows);
  return null;
end;
$$;

create or replace function public.touch_base_workbooks_from_old_rows()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  update public.workbooks as workbook
     set revision = workbook.revision + 1,
         updated_at = now()
   where workbook.id in (select distinct workbook_id from old_rows);
  return null;
end;
$$;

drop trigger if exists base_rows_touch_after_insert on public.base_rows;
create trigger base_rows_touch_after_insert
after insert on public.base_rows
referencing new table as new_rows
for each statement execute function public.touch_base_workbooks_from_new_rows();

drop trigger if exists base_rows_touch_after_update on public.base_rows;
create trigger base_rows_touch_after_update
after update on public.base_rows
referencing new table as new_rows
for each statement execute function public.touch_base_workbooks_from_new_rows();

drop trigger if exists base_rows_touch_after_delete on public.base_rows;
create trigger base_rows_touch_after_delete
after delete on public.base_rows
referencing old table as old_rows
for each statement execute function public.touch_base_workbooks_from_old_rows();

drop trigger if exists base_columns_touch_after_insert on public.base_columns;
create trigger base_columns_touch_after_insert
after insert on public.base_columns
referencing new table as new_rows
for each statement execute function public.touch_base_workbooks_from_new_rows();

drop trigger if exists base_columns_touch_after_update on public.base_columns;
create trigger base_columns_touch_after_update
after update on public.base_columns
referencing new table as new_rows
for each statement execute function public.touch_base_workbooks_from_new_rows();

drop trigger if exists base_columns_touch_after_delete on public.base_columns;
create trigger base_columns_touch_after_delete
after delete on public.base_columns
referencing old table as old_rows
for each statement execute function public.touch_base_workbooks_from_old_rows();

alter table public.base_columns enable row level security;
alter table public.base_rows enable row level security;
alter table public.file_dependencies enable row level security;

commit;
