begin;

create table if not exists public.github_connections (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  installation_id bigint not null check (installation_id > 0),
  repository_full_name text not null check (repository_full_name ~ '^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$'),
  branch text not null default 'main',
  status text not null default 'syncing' check (status in ('syncing', 'active', 'error')),
  last_sync_sha text,
  last_sync_at timestamptz,
  last_error text,
  created_by_email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint github_connections_one_per_project unique (project_id)
);

create index if not exists github_connections_installation_repository_idx
  on public.github_connections (installation_id, repository_full_name);

create table if not exists public.github_template_files (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  github_connection_id bigint not null references public.github_connections(id) on delete cascade,
  repository_full_name text not null,
  path text not null,
  name text not null,
  content text not null,
  blob_sha text not null,
  commit_sha text not null,
  size_bytes bigint not null check (size_bytes >= 0),
  synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint github_template_files_unique_path unique (github_connection_id, path),
  constraint github_template_files_html_only check (lower(path) like '%.html')
);

create index if not exists github_template_files_project_idx
  on public.github_template_files (project_id, path);

create table if not exists public.github_webhook_deliveries (
  id bigint generated by default as identity primary key,
  delivery_id text not null unique,
  event_name text not null,
  repository_full_name text not null,
  installation_id bigint not null,
  status text not null default 'received' check (status in ('received', 'processed', 'ignored', 'error')),
  error text,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists github_webhook_deliveries_received_idx
  on public.github_webhook_deliveries (received_at desc);

create or replace function public.github_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists github_connections_touch_updated_at on public.github_connections;
create trigger github_connections_touch_updated_at
before update on public.github_connections
for each row execute function public.github_touch_updated_at();

drop trigger if exists github_template_files_touch_updated_at on public.github_template_files;
create trigger github_template_files_touch_updated_at
before update on public.github_template_files
for each row execute function public.github_touch_updated_at();

alter table public.github_connections enable row level security;
alter table public.github_template_files enable row level security;
alter table public.github_webhook_deliveries enable row level security;

commit;
