begin;

create extension if not exists pgcrypto;

create table if not exists public.test_time_sessions (
  id uuid primary key default gen_random_uuid(),
  project_id bigint not null references public.projects(id) on delete cascade,
  name text not null default 'Teste de tempo',
  status text not null default 'setup' check (status in ('setup', 'running', 'stopped')),
  started_at timestamptz,
  started_client_epoch_ms numeric(20,3),
  stopped_at timestamptz,
  created_by_email text,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp()
);

create unique index if not exists test_time_sessions_one_open_per_project
  on public.test_time_sessions (project_id)
  where status in ('setup', 'running');

create index if not exists test_time_sessions_project_history_idx
  on public.test_time_sessions (project_id, created_at desc);

create table if not exists public.test_time_groups (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.test_time_sessions(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  workbook_id bigint not null references public.workbooks(id) on delete cascade,
  workbook_name text not null,
  file_kind text not null,
  pipeline_stage text not null,
  stage_number smallint not null check (stage_number between 1 and 4),
  mode text not null check (mode in ('base', 'sheet', 'elementar')),
  group_name text not null,
  reference text not null,
  top_row integer not null check (top_row >= 0),
  bottom_row integer not null check (bottom_row >= top_row),
  left_col integer not null check (left_col >= 0),
  right_col integer not null check (right_col >= left_col),
  last_value_hash text,
  last_value_preview jsonb,
  baseline_at timestamptz,
  last_observed_at timestamptz,
  created_by_email text,
  created_at timestamptz not null default clock_timestamp(),
  updated_at timestamptz not null default clock_timestamp(),
  constraint test_time_groups_reference_unique unique (session_id, workbook_id, group_name, reference)
);

create index if not exists test_time_groups_session_stage_idx
  on public.test_time_groups (session_id, stage_number, workbook_id, id);

create table if not exists public.test_time_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null references public.test_time_sessions(id) on delete cascade,
  group_id bigint not null references public.test_time_groups(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  workbook_id bigint not null references public.workbooks(id) on delete cascade,
  workbook_name text not null,
  file_kind text not null,
  pipeline_stage text not null,
  stage_number smallint not null check (stage_number between 1 and 4),
  group_name text not null,
  reference text not null,
  client_epoch_ms numeric(20,3) not null,
  client_observed_at timestamptz not null,
  server_received_at timestamptz not null default clock_timestamp(),
  value_hash text not null,
  value_preview jsonb,
  changed_cells jsonb not null default '[]'::jsonb check (jsonb_typeof(changed_cells) = 'array'),
  observer_email text
);

create index if not exists test_time_events_timeline_idx
  on public.test_time_events (session_id, client_epoch_ms, id);

create or replace function public.test_time_stage_number(stage text)
returns smallint
language sql
immutable
as $$
  select case stage
    when 'source' then 1
    when 'calculation' then 2
    when 'treated' then 3
    when 'publication' then 4
    else 0
  end::smallint;
$$;

create or replace function public.validate_test_time_group()
returns trigger
language plpgsql
set search_path = public
as $$
declare
  session_row public.test_time_sessions%rowtype;
  workbook_row public.workbooks%rowtype;
  cell_count bigint;
begin
  select * into session_row from public.test_time_sessions where id = new.session_id;
  select * into workbook_row from public.workbooks where id = new.workbook_id;

  if session_row.id is null then
    raise exception 'Sessão Test Time não encontrada.';
  end if;
  if session_row.status not in ('setup', 'running') then
    raise exception 'A sessão Test Time já foi encerrada.';
  end if;
  if workbook_row.id is null or workbook_row.project_id is distinct from session_row.project_id then
    raise exception 'O arquivo monitorado deve pertencer ao projeto do teste.';
  end if;

  cell_count := (new.bottom_row - new.top_row + 1)::bigint
    * (new.right_col - new.left_col + 1)::bigint;
  if cell_count <= 0 or cell_count > 10000 then
    raise exception 'Cada grupo Test Time pode monitorar no máximo 10.000 células.';
  end if;

  new.project_id := session_row.project_id;
  new.workbook_name := workbook_row.name;
  new.file_kind := workbook_row.file_kind;
  new.pipeline_stage := workbook_row.pipeline_stage;
  new.stage_number := public.test_time_stage_number(workbook_row.pipeline_stage);
  new.mode := case
    when workbook_row.pipeline_stage = 'publication' then 'elementar'
    when workbook_row.file_kind = 'base' then 'base'
    else 'sheet'
  end;
  new.updated_at := clock_timestamp();

  if new.stage_number = 0 then
    raise exception 'Etapa de arquivo inválida para Test Time.';
  end if;
  return new;
end;
$$;

drop trigger if exists test_time_groups_validate on public.test_time_groups;
create trigger test_time_groups_validate
before insert or update on public.test_time_groups
for each row execute function public.validate_test_time_group();

create or replace function public.start_test_time_session(
  p_session_id uuid,
  p_client_epoch_ms numeric,
  p_actor text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  session_row public.test_time_sessions%rowtype;
  started timestamptz := clock_timestamp();
begin
  select * into session_row
  from public.test_time_sessions
  where id = p_session_id
  for update;

  if session_row.id is null then
    raise exception 'Sessão Test Time não encontrada.';
  end if;
  if session_row.status = 'stopped' then
    raise exception 'A sessão Test Time já foi encerrada.';
  end if;

  delete from public.test_time_events where session_id = p_session_id;
  update public.test_time_groups
     set last_value_hash = null,
         last_value_preview = null,
         baseline_at = null,
         last_observed_at = null,
         updated_at = started
   where session_id = p_session_id;

  update public.test_time_sessions
     set status = 'running',
         started_at = started,
         started_client_epoch_ms = p_client_epoch_ms,
         stopped_at = null,
         updated_at = started
   where id = p_session_id;

  return jsonb_build_object(
    'id', p_session_id,
    'status', 'running',
    'started_at', started,
    'started_client_epoch_ms', p_client_epoch_ms,
    'actor', p_actor
  );
end;
$$;

create or replace function public.stop_test_time_session(
  p_session_id uuid,
  p_actor text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  stopped timestamptz := clock_timestamp();
  changed integer;
begin
  update public.test_time_sessions
     set status = 'stopped',
         stopped_at = stopped,
         updated_at = stopped
   where id = p_session_id
     and status in ('setup', 'running');
  get diagnostics changed = row_count;

  if changed = 0 then
    raise exception 'Sessão Test Time não encontrada ou já encerrada.';
  end if;

  return jsonb_build_object(
    'id', p_session_id,
    'status', 'stopped',
    'stopped_at', stopped,
    'actor', p_actor
  );
end;
$$;

create or replace function public.observe_test_time_group(
  p_group_id bigint,
  p_value_hash text,
  p_value_preview jsonb,
  p_changed_cells jsonb,
  p_client_epoch_ms numeric,
  p_observer_email text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  group_row public.test_time_groups%rowtype;
  session_row public.test_time_sessions%rowtype;
  received timestamptz := clock_timestamp();
  observed timestamptz;
  event_row public.test_time_events%rowtype;
begin
  if p_value_hash is null or length(p_value_hash) < 16 or length(p_value_hash) > 128 then
    raise exception 'Hash de observação inválido.';
  end if;
  if p_client_epoch_ms is null or p_client_epoch_ms <= 0 then
    raise exception 'Horário de observação inválido.';
  end if;

  select * into group_row
  from public.test_time_groups
  where id = p_group_id
  for update;
  if group_row.id is null then
    raise exception 'Grupo Test Time não encontrado.';
  end if;

  select * into session_row
  from public.test_time_sessions
  where id = group_row.session_id
  for share;
  if session_row.status is distinct from 'running' then
    return jsonb_build_object('status', 'not_running');
  end if;

  observed := to_timestamp((p_client_epoch_ms / 1000)::double precision);

  if group_row.last_value_hash is null then
    update public.test_time_groups
       set last_value_hash = p_value_hash,
           last_value_preview = p_value_preview,
           baseline_at = received,
           last_observed_at = received,
           updated_at = received
     where id = p_group_id;
    return jsonb_build_object(
      'status', 'baseline',
      'group_id', p_group_id,
      'server_received_at', received
    );
  end if;

  if group_row.last_value_hash = p_value_hash then
    update public.test_time_groups
       set last_observed_at = received
     where id = p_group_id;
    return jsonb_build_object('status', 'unchanged', 'group_id', p_group_id);
  end if;

  insert into public.test_time_events (
    session_id,
    group_id,
    project_id,
    workbook_id,
    workbook_name,
    file_kind,
    pipeline_stage,
    stage_number,
    group_name,
    reference,
    client_epoch_ms,
    client_observed_at,
    server_received_at,
    value_hash,
    value_preview,
    changed_cells,
    observer_email
  ) values (
    group_row.session_id,
    group_row.id,
    group_row.project_id,
    group_row.workbook_id,
    group_row.workbook_name,
    group_row.file_kind,
    group_row.pipeline_stage,
    group_row.stage_number,
    group_row.group_name,
    group_row.reference,
    p_client_epoch_ms,
    observed,
    received,
    p_value_hash,
    p_value_preview,
    coalesce(p_changed_cells, '[]'::jsonb),
    p_observer_email
  ) returning * into event_row;

  update public.test_time_groups
     set last_value_hash = p_value_hash,
         last_value_preview = p_value_preview,
         last_observed_at = received,
         updated_at = received
   where id = p_group_id;

  return jsonb_build_object(
    'status', 'event',
    'event_id', event_row.id,
    'group_id', p_group_id,
    'client_epoch_ms', p_client_epoch_ms,
    'server_received_at', received
  );
end;
$$;

revoke all on function public.start_test_time_session(uuid, numeric, text) from public;
revoke all on function public.stop_test_time_session(uuid, text) from public;
revoke all on function public.observe_test_time_group(bigint, text, jsonb, jsonb, numeric, text) from public;
grant execute on function public.start_test_time_session(uuid, numeric, text) to service_role;
grant execute on function public.stop_test_time_session(uuid, text) to service_role;
grant execute on function public.observe_test_time_group(bigint, text, jsonb, jsonb, numeric, text) to service_role;

alter table public.test_time_sessions enable row level security;
alter table public.test_time_groups enable row level security;
alter table public.test_time_events enable row level security;

commit;
