begin;

create table if not exists public.elementar_configs (
  workbook_id bigint primary key references public.workbooks(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  slug text not null unique check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  visibility text not null default 'private' check (visibility in ('private', 'public')),
  public_token text not null unique check (char_length(public_token) >= 32),
  last_publication_id bigint,
  last_publication_version bigint not null default 0 check (last_publication_version >= 0),
  published_at timestamptz,
  created_by_email text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists elementar_configs_project_idx
  on public.elementar_configs (project_id, updated_at desc);

create table if not exists public.elementar_publications (
  id bigint generated by default as identity primary key,
  workbook_id bigint not null references public.elementar_configs(workbook_id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  version bigint not null check (version > 0),
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  definition_revision bigint not null check (definition_revision > 0),
  source_revisions jsonb not null default '{}'::jsonb check (jsonb_typeof(source_revisions) = 'object'),
  declarations jsonb not null default '[]'::jsonb check (jsonb_typeof(declarations) = 'array'),
  created_by_email text not null,
  created_at timestamptz not null default now(),
  constraint elementar_publications_workbook_version_unique unique (workbook_id, version)
);

create index if not exists elementar_publications_workbook_idx
  on public.elementar_publications (workbook_id, version desc);

alter table public.elementar_configs
  drop constraint if exists elementar_configs_last_publication_fk;

alter table public.elementar_configs
  add constraint elementar_configs_last_publication_fk
  foreign key (last_publication_id)
  references public.elementar_publications(id)
  on delete set null;

create or replace function public.elementar_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists elementar_configs_touch_updated_at on public.elementar_configs;
create trigger elementar_configs_touch_updated_at
before update on public.elementar_configs
for each row execute function public.elementar_touch_updated_at();

alter table public.elementar_configs enable row level security;
alter table public.elementar_publications enable row level security;

commit;
