begin;

alter table public.workbook_changes
  add column if not exists op_id uuid,
  add column if not exists client_id text,
  add column if not exists client_seq bigint,
  add column if not exists known_revision bigint,
  add column if not exists operation_kind text not null default 'cells.patch';

create unique index if not exists workbook_changes_workbook_op_id_uidx
  on public.workbook_changes (workbook_id, op_id)
  where op_id is not null;

create index if not exists workbook_changes_workbook_client_seq_idx
  on public.workbook_changes (workbook_id, client_id, client_seq)
  where client_id is not null;

create index if not exists workbook_changes_workbook_revision_idx
  on public.workbook_changes (workbook_id, revision);

create table if not exists public.project_roles (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  name text not null,
  capabilities jsonb not null default '[]'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint project_roles_project_id_name_key unique (project_id, name),
  constraint project_roles_name_format check (name ~ '^[a-z][a-z0-9_-]{1,39}$'),
  constraint project_roles_capabilities_array check (jsonb_typeof(capabilities) = 'array')
);

create table if not exists public.workbook_checkpoints (
  workbook_id bigint not null references public.workbooks(id) on delete cascade,
  revision bigint not null,
  payload jsonb not null,
  created_at timestamptz not null default now(),
  primary key (workbook_id, revision)
);

create table if not exists public.workbook_chunks (
  workbook_id bigint not null references public.workbooks(id) on delete cascade,
  row_chunk integer not null,
  col_chunk integer not null,
  revision bigint not null,
  cells jsonb not null default '[]'::jsonb,
  updated_at timestamptz not null default now(),
  primary key (workbook_id, row_chunk, col_chunk),
  constraint workbook_chunks_nonnegative check (row_chunk >= 0 and col_chunk >= 0),
  constraint workbook_chunks_cells_array check (jsonb_typeof(cells) = 'array')
);

create table if not exists public.workbook_telemetry_samples (
  id bigint generated by default as identity primary key,
  workbook_id bigint not null references public.workbooks(id) on delete cascade,
  project_id bigint not null references public.projects(id) on delete cascade,
  revision bigint not null default 0,
  user_email text not null,
  client_version text,
  metrics jsonb not null,
  created_at timestamptz not null default now(),
  constraint workbook_telemetry_metrics_object check (jsonb_typeof(metrics) = 'object')
);

create index if not exists workbook_telemetry_samples_project_created_idx
  on public.workbook_telemetry_samples (project_id, created_at desc);

create index if not exists workbook_telemetry_samples_workbook_created_idx
  on public.workbook_telemetry_samples (workbook_id, created_at desc);

create or replace view public.workbook_telemetry_latest as
select distinct on (workbook_id)
  workbook_id,
  project_id,
  revision,
  metrics,
  client_version,
  user_email,
  created_at
from public.workbook_telemetry_samples
order by workbook_id, created_at desc;

create or replace function public.architecture_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists project_roles_touch_updated_at on public.project_roles;
create trigger project_roles_touch_updated_at
before update on public.project_roles
for each row execute function public.architecture_touch_updated_at();

drop trigger if exists workbook_chunks_touch_updated_at on public.workbook_chunks;
create trigger workbook_chunks_touch_updated_at
before update on public.workbook_chunks
for each row execute function public.architecture_touch_updated_at();

commit;
