begin;

alter table public.elementar_configs
  add column if not exists auto_publish boolean not null default true;

alter table public.elementar_configs
  add column if not exists last_payload_hash text;

alter table public.elementar_publications
  add column if not exists payload_hash text;

create index if not exists elementar_publications_payload_hash_idx
  on public.elementar_publications (workbook_id, payload_hash, version desc);

create table if not exists public.elementar_dependencies (
  id bigint generated by default as identity primary key,
  elementar_workbook_id bigint not null references public.elementar_configs(workbook_id) on delete cascade,
  source_workbook_id bigint not null references public.workbooks(id) on delete cascade,
  declaration_key text not null,
  workbook_name text not null,
  source_range text not null,
  declaration_cell text,
  declaration_order integer not null check (declaration_order >= 0),
  top_row integer not null check (top_row >= 0),
  bottom_row integer not null check (bottom_row >= top_row),
  left_col integer not null check (left_col >= 0),
  right_col integer not null check (right_col >= left_col),
  definition_revision bigint not null check (definition_revision > 0),
  last_value jsonb,
  last_source_revision bigint not null default 0 check (last_source_revision >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint elementar_dependencies_key_unique unique (elementar_workbook_id, declaration_key)
);

create index if not exists elementar_dependencies_source_idx
  on public.elementar_dependencies (source_workbook_id, elementar_workbook_id);

create index if not exists elementar_dependencies_elementar_idx
  on public.elementar_dependencies (elementar_workbook_id, declaration_order);

create table if not exists public.elementar_source_snapshots (
  source_workbook_id bigint primary key references public.workbooks(id) on delete cascade,
  revision bigint not null check (revision >= 0),
  payload jsonb not null check (jsonb_typeof(payload) = 'object'),
  payload_hash text not null,
  updated_by_email text,
  updated_at timestamptz not null default now()
);

create index if not exists elementar_source_snapshots_revision_idx
  on public.elementar_source_snapshots (source_workbook_id, revision desc);

alter table public.elementar_dependencies enable row level security;
alter table public.elementar_source_snapshots enable row level security;

commit;
